clients_app/urls.py
from django.urls import path
from . import views

app_name = "clients_app"
urlpatterns = [
    path("list/", views.ClientListView.as_view(), name="list"),
    path("create/", views.clients_create, name="create"),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
]

clients_project/urls.py
from django.contrib import admin
from django.urls import path, include
from clients_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('clients/', include('clients_app.urls')),
]

clients_app/models.py
from django.db import models
from django.contrib.auth.models import User


class Client(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.EmailField(unique=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='profile_pics', blank=True, null=True)
    profile_url = models.URLField(max_length=200, blank=True)

    def __str__(self):
        return self.user.username

clients_app/forms.py
from django import forms
from .models import Client
from django.contrib.auth.models import User
from .models import Profile


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = "__all__"


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('photo', 'profile_url')

clients_app/views.py
from django.shortcuts import redirect, render
from .models import Client
from .forms import ClientForm, ProfileForm, UserRegistrationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.views.generic.list import ListView
from django.utils.decorators import method_decorator


@method_decorator(login_required, name="dispatch")
class ClientListView(ListView):
    model = Client
    ordering = ['-id']
    context_object_name = 'clients'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["nbar"] = 'list'
        return context


def index(request):
    return render(request, "clients_app/index.html")


@login_required
def clients_create(request):
    form = ClientForm()
    if request.method == "POST":
        form = ClientForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return redirect('clients_app:list')
    return render(request, "clients_app/clients_create.html", {"form": form, 'nbar': 'create'})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                # Redirect to a home page or dashboard
                return redirect('index')
            else:
                messages.error(request, 'Invalid username or password.')
        else:
            messages.error(request, 'Invalid username or password.')
    else:
        form = AuthenticationForm()

    return render(request, 'clients_app/login.html', {'form': form, 'nbar': 'login'})


def logout_view(request):
    logout(request)
    return redirect('clients_app:login')  # Redirect to login page after logout


def register_view(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        profile_form = ProfileForm(request.POST, request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save(commit=False)
            user.set_password(user_form.cleaned_data['password'])
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            login(request, user)
            return redirect('index')
    else:
        user_form = UserRegistrationForm()
        profile_form = ProfileForm()
    return render(request, 'clients_app/register.html', {'user_form': user_form, 'profile_form': profile_form, 'nbar': 'register'})

clients_app/templates/clients_app/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title_block %}
    {% endblock%}

</head>

<body>

    <nav class="navbar navbar-expand-lg  navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'index' %}">Home</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link {% if nbar == 'list' %}active{% endif %}"
                        href="{% url 'clients_app:list' %}">List Clients</a>
                    <a class="nav-link {% if nbar == 'create' %}active{% endif %}"
                        href="{% url 'clients_app:create' %}">Create Client</a>
                    <a class="nav-link" href="{% url 'admin:index' %}" target="_blank">Admin Panel</a>
                    {% if user.is_authenticated %}
                    <li class="navbar-text">{{ user.username }}</li>
                    <a class="nav-link" href="{% url 'clients_app:logout' %}">Logout</a>
                    {% else %}
                    <a class="nav-link {% if nbar == 'login' %}active{% endif %}"
                        href="{% url 'clients_app:login' %}">Login</a>
                    <a class="nav-link {% if nbar == 'register' %}active{% endif %}"
                        href="{% url 'clients_app:register' %}">Register</a>

                    {% endif %}


                </div>
            </div>
        </div>
    </nav>
    <div class="container py-4">
        {% block body_block %}
        {% endblock%}
    </div>
</body>

</html>

clients_app/templates/clients_app/client_list.html
{% extends 'clients_app/base.html' %}

{% block title_block %}
<title>List Clients</title>
{% endblock%}

{% block body_block %}
<h1>List of Clients</h1>

<table class="table table-striped table-bordered">
    <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
    </tr>
    {% for client in clients %}
    <tr>
        <td>{{ client.first_name }}</td>
        <td>{{ client.last_name }}</td>
        <td>{{ client.email }}</td>
    </tr>
    {% endfor %}
</table>

{% endblock %}

clients_app/templates/clients_app/clients_create.html
{% extends 'clients_app/base.html' %}

{% block title_block %}
<title>Create Client</title>
{% endblock%}

{% block body_block %}

<h1>Create a new client</h1>
<form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" class="btn btn-primary" value="Create">
</form>

{% endblock %}

clients_app/templates/clients_app/clients_list.html
{% extends 'clients_app/base.html' %}

{% block title_block %}
<title>List Clients</title>
{% endblock%}

{% block body_block %}
<h1>List of Clients</h1>

<table class="table table-striped table-bordered">
    <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
    </tr>
    {% for client in clients %}
    <tr>
        <td>{{ client.first_name }}</td>
        <td>{{ client.last_name }}</td>
        <td>{{ client.email }}</td>
    </tr>
    {% endfor %}
</table>

{% endblock %}

clients_app/templates/clients_app/index.html
{% extends 'clients_app/base.html' %}

{% block title_block %}
<title>Home</title>
{% endblock%}

{% block body_block %}
<div class="container py-4">
    <div class="p-5 mb-4 bg-light rounded-3">
        <div class="container-fluid py-5">
            <h1 class="display-5 fw-bold">Welcome to Clients App</h1>
            <ul>
                <li class="col-md-8 fs-4">Go to <a href="{% url 'clients_app:list' %}">/clients/list</a> to see the
                    list of
                    clients.</li>
                <li class="col-md-8 fs-4">Go to <a href="{% url 'clients_app:create' %}">/clients/create</a> to
                    create a client.
                <li class="col-md-8 fs-4">Here is <a href="{% url 'admin:index' %}" target="_blank">Admin Page</a>.
                </li>
            </ul>
        </div>
    </div>
</div>

{% endblock %}

clients_app/templates/clients_app/login.html
{% extends 'clients_app/base.html' %}

{% block title_block %}
<title>Login</title>
{% endblock%}

{% block body_block %}
<h2>Login</h2>
{% if messages %}
<ul>
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="Login">
</form>

{% endblock %}

clients_app/templates/clients_app/register.html
{% extends 'clients_app/base.html' %}

{% block title_block %}
<title>Register</title>
{% endblock%}

{% block body_block %}
<h2>Register</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
        {{ user_form.as_p }}
    </div>
    <div>
        {{ profile_form.as_p }}
    </div>
    <input type="submit" class="btn btn-primary" value="Register">
</form>
{% endblock %}